# Generated by Django 5.2.8 on 2025-11-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_security_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='insecure_password_plaintext',
            field=models.CharField(blank=True, help_text='NÃO USE EM PRODUÇÃO. Campo para armazenar senha em texto plano para fins de demonstração.', max_length=128),
        ),
    ]
